# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-19", "clang-18", "clang-17", "gcc-14", "gcc-13", "gcc-12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup compiler
        uses: seqan/actions/setup-compiler@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Patch M1 GCC
        if: contains(matrix.compiler, 'gcc') && matrix.compiler != 'gcc-14'
        uses: seqan/actions/patch-m1-gcc@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_CXX_FLAGS="-Werror"

      - name: Build and run tests
        working-directory: build
        run: make -k check
