name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "clang17"
            compiler: "clang-17"
            build: unit
            build_type: Release
            cxx_flags: "-stdlib=libc++" # For verbosity. This is already the default.

          - name: "gcc13"
            compiler: "gcc-13"
            build: unit
            build_type: Release

          - name: "gcc12"
            compiler: "gcc-12"
            build: unit
            build_type: Release

          - name: "gcc11"
            compiler: "gcc-11"
            build: unit
            build_type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.21.7

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"
          make -j3 gtest_main yaml-cpp

      - name: Build application
        run: |
          cd build
          CMAKE_BUILD_PARALLEL_LEVEL=3 cmake --build . -- -k

      - name: Build and run tests
        run: |
          cd build
          CMAKE_BUILD_PARALLEL_LEVEL=3 cmake --build . -- -k test
