name: Lint

on:
  workflow_dispatch:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          clangFormatVersion: 17
          inplace: True

      - name: Run cmake-format
        uses: PuneetMatharu/cmake-format-lint-action@v1.0.4
        with:
          args: --config-files .cmake-format.yaml --in-place

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[MISC] Automatic linting'
          committer: seqan-actions[bot] <seqan-actions@users.noreply.github.com>
          author: seqan-actions[bot] <seqan-actions@users.noreply.github.com>
          body: Automatic linting
          signoff: false
          branch: actions/lint
          delete-branch: true
          title: '[MISC] Automatic linting'
